name: Android Build

# 触发条件，这里设置为 push 到 main 分支或者手动触发工作流
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码到运行环境
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置 Java 环境，这里使用 OpenJDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 第三步：授予 Gradle 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 第四步：使用 Gradle 进行项目构建，生成 APK 文件
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # 第五步：上传生成的 APK 文件作为工作流的产物，方便后续下载
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
